### ISSUE TITLE
"Could not find docmap.json" error

### ISSUE THREAD

**Issue by Aninsi-Sasberg** [davidgranstrom/telescope-scdoc.nvim#7]
When I execute `:Telescope scdoc` i get the following error log:
```lua
Error executing vim.schedule lua callback: ...cope-scdoc.nvim/lua/telescope/_extensions/scdoc/main.lua:22: ...user/.local/share/nvim/lazy/scnvim/lua/scnvim
/help.lua:191: Could not find docmap.json
stack traceback:
        [C]: in function 'error'
        ...cope-scdoc.nvim/lua/telescope/_extensions/scdoc/main.lua:22: in function 'callback'
        .../aninsi/.local/share/nvim/lazy/scnvim/lua/scnvim/udp.lua:38: in function 'func'
        .../aninsi/.local/share/nvim/lazy/scnvim/lua/scnvim/udp.lua:53: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I suppose this is not a configuration problem, as telescope-scdoc is being called, but the formatting of `docmap.json` or the location is wrong(?).
I just have peeked into telescope-scdoc's `main.lua` (starting at line 18) and into scnvim's `help.lua` (`get_docmap` function). While I am not too familiar with lua itself, I get that it has to do with checking either the path or the contents of `docmap` (which would mean the `get_docmap` can't read/find the `docmap.json` at the given `path`).

I wouldn't rule out the possibility that my configuration is wrong, but I have tried different ways, and the error persists. If this is a bug I am happy to give more information and help to get it sorted out, but as I said, if you suspect it has to do with my configuration I will check it once more.

Thanks for the great Plug-In ecosystem supporting Supercollider in Neovim!

-Aninsi Sasberg

**Comment by davidgranstrom** [comment]
@Aninsi-Sasberg Thanks for the report.

`docmap.json` should be auto-generated once you try and access any (sc)help file via the help system using scnvim, another solution is to call `SCNvimDoc.indexAllDocuments` from a supercollider buffer to generate said file. You will find the resulting file in the location given by `SCDoc.helpTargetDir`.

One improvement would be if the `get_docmap` function actually generated the file if not found.. I also noticed a cache miss in the same function that could be easily fixed so I'll create an issue for this on the `scnvim` issue tracker.

Let me know if your problem persists after trying the solution(s) above.

**Comment by Aninsi-Sasberg** [comment]
Thank you for your swift reply!
It worked by calling
> `SCNvimDoc.indexAllDocuments` from a supercollider buffer

so thanks for the tip! Happy I could help in giving you ideas for improving scnvim. :)
